### ISSUE TITLE
Code about Photo-realistic Rendering of 3D objects

### ISSUE THREAD

**Issue by Gary-code** [VICO-UoE/Looking3D#2]
Nice work in CVPR 2024. Could you provide the code for Photo-realistic Rendering of 3D objects, as mentioned in the [27] in the paper.

**Comment by ankanbhunia** [comment]
Sorry for the late reply. 

I have uploaded the codes for rendering in the following repository. 

[https://github.com/ankanbhunia/realistic-render-engine](https://github.com/ankanbhunia/realistic-render-engine)

I hope it helps.
